### ISSUE TITLE
Original bot is in C#, not C++

### ISSUE THREAD

**Issue by plasticuproject** [aroe-s-community/pythonJarvis#9]
In your description you say `Let's revamp Jarvis because he's written in c++ and we all collectively hate c++ `, when the original bot is in C#, not C++. We hate C#. C++ is _okay_, but we (I) really dislike C#.

**Comment by aroesec** [comment]
This is good feedback. I actually now love C++ and want to change it immediately

**Comment by plasticuproject** [comment]
You are confusing me. I was letting you know that _this_ repository description is inaccurate. The original bot that you are referencing ![here](https://github.com/aroesec/jarvis) is written in C#, not C++ as the description of this repository says. The original bot is in C#.

You should change the description of this repository to say the following:
`Let's revamp Jarvis because he's written in C# and we all collectively hate C# `

**Comment by aroesec** [comment]
yes

**Comment by aroesec** [comment]
done!

**Comment by aroesec** [comment]
Done!

**Comment by aroesec** [comment]
fixed
